// Auto-generated contract addresses for sepolia network
// Do not edit this file manually - it's generated by build.js

export const vaultAddress = "0xD4aD288de412Ef61435BAb420dF9d5a61f6f0659";
export const sirAddress = "0x7Fa77a8D7Fb89bad4df149912f9d3B0d449Ee63b";
export const zeroAddress = "0x0000000000000000000000000000000000000000";

// Uniswap V3 Factory (same address on all networks)
export const uniswapV3FactoryAddress = "0x0227628f3F023bb0B980b67D528571c95c6DaC1c";

// Network-specific token addresses
export const usdcAddress = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238";
export const wethAddress = "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14";
